# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# zsh theme
ZSH_THEME="gianu"

# plugins
plugins=(git
zsh-autosuggestions
zsh-syntax-highlighting
zsh-history-substring-search
)

# oh my zsh
source $ZSH/oh-my-zsh.sh

# fix cursor
_fix_cursor() {
   echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)

# add cargo to path
export PATH="$HOME/.cargo/bin:$PATH"
