export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

ZSH_THEME="gianu"

plugins=(git
zsh-autosuggestions
zsh-syntax-highlighting
zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

start-ssh-agent() {
  eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519
}
