live_config_reload = true

[colors.bright]
black = "0x535c64"
blue = "0x2a7bde"
cyan = "0x33c7de"
green = "0x33d17a"
magenta = "0xc061cb"
red = "0xf66151"
white = "0xffffff"
yellow = "0xe9ad0c"

[colors.normal]
black = "0x171421"
blue = "0x12488b"
cyan = "0x2aa1b3"
green = "0x26a269"
magenta = "0xa347ba"
red = "0xc01c28"
white = "0xd0cfcc"
yellow = "0xa2734c"

[colors.primary]
background = "#1e1e1e"
foreground = "#ffffff"

[cursor]
style = "Beam"

[font]
size = 11.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
dynamic_padding = false
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 95
lines = 26

[window.padding]
x = 0
y = 0
